version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: ems-postgres-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: yourpassword
      POSTGRES_DB: loginapp
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

  backend:
    build:
      context: ./backend
    container_name: ems-backend-server
    ports:
      - "5001:5001"
    environment:
      PORT: 5001
      DATABASE_URL: "postgresql://postgres:yourpassword@db:5432/loginapp?schema=public"
      JWT_SECRET: "supersecretkey123"
      JWT_REFRESH_SECRET: "supersecretrefreshkey123"
      NODE_ENV: "production"
    depends_on:
      - db
    restart: always

  frontend:
    build:
      context: ./frontend
    container_name: ems-frontend-app
    ports:
      - "8080:80"
    depends_on:
      - backend
    restart: always

volumes:
  pgdata:
